//! Reports view — session selector and generated report preview.
//!
//! Left pane: session list for report selection.
//! Right pane: Markdown report preview (generated by TuiApp via sigint-report).

use ratatui::layout::{Constraint, Direction, Layout, Rect};
use ratatui::style::{Color, Modifier, Style};
use ratatui::text::{Line, Span};
use ratatui::widgets::{Block, Borders, Cell, Paragraph, Row, Table, Wrap};
use ratatui::Frame;

use crate::state::{AppState, Panel};

/// Render the Reports view into `area`.
pub fn render(frame: &mut Frame, state: &AppState, area: Rect) {
    let layout = Layout::default()
        .direction(Direction::Horizontal)
        .constraints([Constraint::Percentage(30), Constraint::Percentage(70)])
        .split(area);

    render_report_list(frame, state, layout[0]);
    render_report_preview(frame, state, layout[1]);
}

fn render_report_list(frame: &mut Frame, state: &AppState, area: Rect) {
    let focused = state.focused_panel == Panel::ReportList;
    let border_style = if focused {
        Style::default().fg(Color::Cyan)
    } else {
        Style::default().fg(Color::DarkGray)
    };

    let rows: Vec<Row> = state
        .report_list
        .iter()
        .enumerate()
        .map(|(i, s)| {
            let row = Row::new(vec![
                Cell::from(s.target.clone().unwrap_or_else(|| "-".into())),
                Cell::from(s.created_at.format("%m-%d").to_string()),
            ]);
            if i == state.selected_report_idx {
                row.style(
                    Style::default()
                        .fg(Color::Black)
                        .bg(Color::Cyan)
                        .add_modifier(Modifier::BOLD),
                )
            } else {
                row
            }
        })
        .collect();

    let table = Table::new(rows, [Constraint::Min(14), Constraint::Length(6)])
        .header(Row::new(["TARGET", "DATE"]).style(Style::default().add_modifier(Modifier::BOLD)))
        .block(
            Block::default()
                .title(" Sessions ")
                .borders(Borders::ALL)
                .border_style(border_style),
        );

    let hint = if state.report_list.is_empty() {
        Paragraph::new("No sessions — run a scan first")
            .style(Style::default().fg(Color::DarkGray))
            .block(
                Block::default()
                    .title(" Sessions ")
                    .borders(Borders::ALL)
                    .border_style(border_style),
            )
    } else {
        // Render the table widget instead.
        frame.render_widget(table, area);
        return;
    };

    frame.render_widget(hint, area);
}

fn render_report_preview(frame: &mut Frame, state: &AppState, area: Rect) {
    let focused = state.focused_panel == Panel::ReportPreview;
    let border_style = if focused {
        Style::default().fg(Color::Cyan)
    } else {
        Style::default().fg(Color::DarkGray)
    };

    if state.report_preview.is_empty() {
        let help_lines = vec![
            Line::from(Span::styled(
                "No report generated yet.",
                Style::default().fg(Color::DarkGray),
            )),
            Line::default(),
            Line::from("  • Select a session on the left"),
            Line::from("  • Press Enter to generate a Markdown report"),
            Line::from("  • Use  :report export <path>  to save to disk"),
        ];
        let placeholder = Paragraph::new(help_lines).block(
            Block::default()
                .title(" Report Preview ")
                .borders(Borders::ALL)
                .border_style(border_style),
        );
        frame.render_widget(placeholder, area);
        return;
    }

    // Render Markdown as plain lines (no syntax highlighting — terminal width limited).
    let lines: Vec<Line> = state
        .report_preview
        .lines()
        .map(|l| {
            if l.starts_with("## ") || l.starts_with("# ") {
                Line::from(Span::styled(
                    l.to_string(),
                    Style::default()
                        .fg(Color::Cyan)
                        .add_modifier(Modifier::BOLD),
                ))
            } else if l.starts_with("### ") {
                Line::from(Span::styled(
                    l.to_string(),
                    Style::default()
                        .fg(Color::White)
                        .add_modifier(Modifier::BOLD),
                ))
            } else if l.starts_with("- ") || l.starts_with("* ") {
                Line::from(vec![
                    Span::styled("  • ", Style::default().fg(Color::Yellow)),
                    Span::raw(l[2..].to_string()),
                ])
            } else {
                Line::from(l.to_string())
            }
        })
        .collect();

    let scroll_up = state
        .scroll_offsets
        .get(&Panel::ReportPreview)
        .copied()
        .unwrap_or(0);
    let inner_height = area.height.saturating_sub(2) as usize;
    let bottom = lines.len().saturating_sub(inner_height);
    let vertical = if scroll_up == 0 {
        bottom as u16
    } else {
        bottom.saturating_sub(scroll_up) as u16
    };

    let preview = Paragraph::new(lines)
        .block(
            Block::default()
                .title(" Report Preview ")
                .borders(Borders::ALL)
                .border_style(border_style),
        )
        .wrap(Wrap { trim: false })
        .scroll((vertical, 0));

    frame.render_widget(preview, area);
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state::AppState;
    use ratatui::backend::TestBackend;
    use ratatui::Terminal;

    #[test]
    fn render_empty_reports_view_does_not_panic() {
        let backend = TestBackend::new(120, 30);
        let mut terminal = Terminal::new(backend).unwrap();
        let state = AppState::new();
        terminal
            .draw(|frame| render(frame, &state, frame.area()))
            .unwrap();
    }

    #[test]
    fn render_report_preview_with_markdown_does_not_panic() {
        let backend = TestBackend::new(120, 30);
        let mut terminal = Terminal::new(backend).unwrap();
        let mut state = AppState::new();
        state.report_preview = "# SIGINT Scan Report\n\n## Executive Summary\n\nFound 3 findings.\n\n### Findings\n\n- XSS (High)\n- SQLi (Critical)\n".into();
        terminal
            .draw(|frame| render(frame, &state, frame.area()))
            .unwrap();
    }

    #[test]
    fn render_reports_with_session_list_does_not_panic() {
        use sigint_core::types::Session;

        let backend = TestBackend::new(120, 30);
        let mut terminal = Terminal::new(backend).unwrap();
        let mut state = AppState::new();
        state.report_list = vec![
            Session::new("scan-a").with_target("example.com"),
            Session::new("scan-b").with_target("10.0.0.1"),
        ];
        state.selected_report_idx = 0;
        terminal
            .draw(|frame| render(frame, &state, frame.area()))
            .unwrap();
    }
}
