[package]
name = "sigint-recon"
version.workspace = true
edition.workspace = true

[dependencies]
sigint-core = { workspace = true }
sigint-store = { workspace = true }
sigint-sandbox = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
reqwest = { workspace = true }
ipnet = { workspace = true }
regex = "1"
